package Componants;

/**
 *
 * @author DigitalNet
 */
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.*;
import InputOutFiles.*;
import java.beans.PropertyChangeSupport;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author jasam sheja
 */
public class TheGamePanel extends javax.swing.JPanel {

    /**
     * Creates new form testJtable
     */
    public TheGamePanel() {
        initMyComponents();
        initComponents();
    }

    public TheGamePanel(Level level) {
        this.level = level;
        initMyComponents();
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        //setSize(300, 320);

        
        this.setBackground(Color.DARK_GRAY);
        GridLayout gridLayout = new GridLayout(mybuttons.length, mybuttons.length, 0, 0);
        this.setLayout(gridLayout);
        for (CellPanel[] buttons : mybuttons) {
            for (CellPanel button : buttons) {
                this.add(button);
            }
        }
        
        moves = 0;

    }// </editor-fold>                        

    private void initMyComponents() {
//        Dot[] dots = new Dot[4];
//        dots[0] = new Dot(Color.BLUE, 0, 0, Color.BLUE, 0, 3);
//        dots[1] = dots[0].next;
//        dots[2] = new Dot(Color.yellow, 2, 2, Color.yellow, 1, 1);
//        dots[3] = dots[2].next;
//        level = new Level(dots, new Bridge(3, 3), new Hall(3, 0), 5, 1);
//        gc = new GameControllar(level);
        level = GReader.levelsReader(1, "LevelTest.bin");
        Dot[] dots =  level.getDots() ;
        gc = new GameControllar(level);
        for (int i = 0; i < gc.CellsPerRow(); i++) {
            final int fi = i;
            for (int j = 0; j < gc.CellsPerRow(); j++) {
                final int fj = j;
//                Cell cell = cells[i][j];
                gc.addPropertyChangeListner(new PropertyChangeListener() {
                    @Override
                    public void propertyChange(PropertyChangeEvent evt) {
                        Cell.State state = (Cell.State) evt.getNewValue();
                        Cell thecell = (Cell) evt.getOldValue();
                        boolean hasPipe = state == Cell.State.CROSS_ENTERD
                                || state == Cell.State.ENTERD
                                || state == Cell.State.CROSS_LEAVED
                                || state == Cell.State.LEAVED;
                        Color color = null;
                        switch (evt.getPropertyName()) {
                            case "UP":
                                if (hasPipe) {
                                    color = thecell.getColor(Cell.Side.UP);
                                }
                                mybuttons[fi][fj].setDrawUp(hasPipe, color);
                                break;
                            case "DOWN":
                                if (hasPipe) {
                                    color = thecell.getColor(Cell.Side.DOWN);
                                }
                                mybuttons[fi][fj].setDrawDown(hasPipe, color);
                                break;
                            case "RIGHT":
                                if (hasPipe) {
                                    color = thecell.getColor(Cell.Side.RIGHT);
                                }
                                mybuttons[fi][fj].setDrawRight(hasPipe, color);
                                break;
                            case "LEFT":
                                if (hasPipe) {
                                    color = thecell.getColor(Cell.Side.LEFT);
                                }
                                mybuttons[fi][fj].setDrawLeft(hasPipe, color);
                                break;
                        }
                    }
                }, i, j);
            }
        }
        gc.addPropertyChangeListner(new PropertyChangeListener() {

            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                if(evt.getPropertyName().equalsIgnoreCase("unfilled")){
                    changeSupport.firePropertyChange("finished", false, true);
                }else if(evt.getPropertyName().equalsIgnoreCase("maze")){
                    int length = ((Maze)evt.getNewValue()).getLength();
                    for (int k = 0; k < length; k++) {
                        for (int l = 0; l < length; l++) {
                            Cell theCell = ((Maze) evt.getNewValue()).getCellAt(k, l);
                            
                            boolean up = false,down = false,left = false,right = false;
                            Cell.Side side = theCell.getEntered(true);
                            if(side != null)
                                switch(side){
                                    case RIGHT:
                                        right = true;
                                        break;
                                    case LEFT:
                                        left = true;
                                        break;
                                }
                            side = theCell.getLeaved(true);
                            if(side != null)
                                switch(side){
                                    case RIGHT:
                                        right = true;
                                        break;
                                    case LEFT:
                                        left = true;
                                        break;
                                }
                            side = theCell.getEntered(false);
                            if(side != null)
                                switch(side){
                                    case UP:
                                        up = true;
                                        break;
                                    case DOWN:
                                        down = true;
                                        break;
                                }
                            side = theCell.getLeaved(false);
                            if(side != null)
                                switch(side){
                                    case UP:
                                        up = true;
                                        break;
                                    case DOWN:
                                        down = true;
                                        break;
                                }
                            mybuttons[k][l].setDrawUp(up, theCell.getColor(Cell.Side.UP));
                            mybuttons[k][l].setDrawDown(down, theCell.getColor(Cell.Side.DOWN));
                            mybuttons[k][l].setDrawRight(right, theCell.getColor(Cell.Side.RIGHT));
                            mybuttons[k][l].setDrawLeft(left, theCell.getColor(Cell.Side.LEFT));
                        
                        }
                    }
                }
            }
        });
        mybuttons = new CellPanel[level.getLength()][level.getLength()];
        int k = 0;
        for (int l = 0; l < mybuttons.length; l++) {
            final int fi = l;
            for (int m = 0; m < mybuttons.length; m++) {
                final int fj = m;
                if ((k < dots.length) && (dots[k].x == l && dots[k].y == m)) {
                    mybuttons[l][m] = new CellPanel(l, m, true, false, false, dots[k].color);
                    k++;
                } else if (level.getBridge() != null && level.getBridge().x == l && level.getBridge().y == m) {
                    mybuttons[l][m] = new CellPanel(l, m, false, true, false, null);
                } else if (level.getHall() != null && level.getHall().x == l && level.getHall().y == m) {
                    mybuttons[l][m] = new CellPanel(l, m, false, false, true, null);
                } else {
                    mybuttons[l][m] = new CellPanel(l, m, false, false, false, null);
                }
                mybuttons[l][m].addMouseListener(new myCellPanelListener(l, m) {
                    @Override
                    public void mouseEntered(java.awt.event.MouseEvent evt) {
                        if (ismousePressed) {
                            canAdd = (Math.abs(mybuttons[fi][fj].getRowIndex() - i0) + Math.abs(mybuttons[fi][fj].getColomunIndex() - j0)) == 1;
                            if(canAdd){
                                try {
                                    if (!gc.add(mybuttons[fi][fj].getRowIndex(), mybuttons[fi][fj].getColomunIndex(), i0, j0)) {
                                        canAdd = false;
                                    }
                                } catch (IllegalArgumentException e) {
                                    if ("moving horezentaly or verticaly only".equals(e.getMessage())) {
                                        canAdd = false;
                                    }
                                }
                            }
                        } 
                    }

                    @Override
                    public void mouseExited(java.awt.event.MouseEvent evt) {
                        if (ismousePressed && canAdd) {
                            i0 = mybuttons[fi][fj].getRowIndex();
                            j0 = mybuttons[fi][fj].getColomunIndex();
                        }
                    }

                    @Override
                    public void mousePressed(java.awt.event.MouseEvent evt) {
                        if (evt.getButton() == MouseEvent.BUTTON1) {
                            ismousePressed = true;
                            gc.saveState();
                            i0 = mybuttons[fi][fj].getRowIndex();
                            j0 = mybuttons[fi][fj].getColomunIndex();
                            color = mybuttons[fi][fj].getColor(true);
                            canAdd = color!=null;
                            if(canAdd)
                                gc.clearPath(i0, j0);                            
                        }
                    }

                    @Override
                    public void mouseReleased(java.awt.event.MouseEvent evt) {
                        if (evt.getButton() == MouseEvent.BUTTON1) {
                            if(ismousePressed && changeSupport!=null){
                                changeSupport.firePropertyChange("MOVES", moves++, moves);
                            }
                                
                            i0 = -10;
                            j0 = -10;
                            ismousePressed = false;
                            canAdd = false;
                            color = null;
                        }
                    }
                });

            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TheGamePanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JFrame frame = new JFrame("testing");
                frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                
                TheGamePanel gamePanel =  new TheGamePanel();
                frame.setSize(300, 320);
                frame.add(gamePanel, BorderLayout.CENTER);
                frame.setVisible(true);
            }
        });
    }

    private int i, j, i0=-10, j0=-10;
    private boolean ismousePressed;
    private boolean canAdd;
    private Color color;
    
    private GameControllar gc;
    private CellPanel[][] mybuttons;
    private Level level;
    
    private int moves;
    
    private PropertyChangeSupport changeSupport;
    
    public void addListener(PropertyChangeListener listener){
        if (listener == null) {
            return;
        }
        if (changeSupport == null) {
            changeSupport = new PropertyChangeSupport(this);
        }
        changeSupport.addPropertyChangeListener(listener);
    }

    private class myCellPanelListener extends MouseAdapter {

        private final int i, j;
        boolean ispressed;

        public myCellPanelListener(int i, int j) {
            this.i = i;
            this.j = j;
        }

        public void setIsPressed(boolean bool) {
            ispressed = bool;
        }

        @Override
        public void mouseExited(MouseEvent e) {
            super.mouseExited(e); //To change body of generated methods, choose Tools | Templates.
        }

        @Override
        public void mouseEntered(MouseEvent e) {
            super.mouseEntered(e); //To change body of generated methods, choose Tools | Templates.
        }

        @Override
        public void mouseReleased(MouseEvent e) {
            super.mouseReleased(e); //To change body of generated methods, choose Tools | Templates.
        }

        @Override
        public void mousePressed(MouseEvent e) {
            super.mousePressed(e); //To change body of generated methods, choose Tools | Templates.
        }

    }
    
    public GameControllar getGameControllar(){
        return gc;
    }
    public void increaseMoves(){
        changeSupport.firePropertyChange("moves", moves++, moves);
    }
    public void decreaseMoves(){
        changeSupport.firePropertyChange("moves", moves--, moves);
    }
}
